// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD27Ux-lJt7oeva4mxn1GF4ta0Yx0CC0f0',
    appId: '1:305876215113:web:07dbce705d0a35b18f6698',
    messagingSenderId: '305876215113',
    projectId: 'notes-258f8',
    authDomain: 'notes-258f8.firebaseapp.com',
    storageBucket: 'notes-258f8.firebasestorage.app',
    measurementId: 'G-ZGWJGYYB44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV_HeirRe32b3SRstjQWdjIk3aP7MF24w',
    appId: '1:305876215113:android:4f323b2e368ec0fe8f6698',
    messagingSenderId: '305876215113',
    projectId: 'notes-258f8',
    storageBucket: 'notes-258f8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD27Ux-lJt7oeva4mxn1GF4ta0Yx0CC0f0',
    appId: '1:305876215113:web:83a8b56acdc4dd598f6698',
    messagingSenderId: '305876215113',
    projectId: 'notes-258f8',
    authDomain: 'notes-258f8.firebaseapp.com',
    storageBucket: 'notes-258f8.firebasestorage.app',
    measurementId: 'G-9YVH1DWCT5',
  );
}