// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO0H1SXf6J5hNusuuWxUA8OkTTp8IAb_Y',
    appId: '1:711457422776:web:03b98ae832d285c808634d',
    messagingSenderId: '711457422776',
    projectId: 'cepuapp-35e84',
    authDomain: 'cepuapp-35e84.firebaseapp.com',
    storageBucket: 'cepuapp-35e84.firebasestorage.app',
    measurementId: 'G-DRZCDYDBC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_92M6Vs1M14R8mb8jBbPLqWt9F5gKOGs',
    appId: '1:711457422776:android:2e5f61ad664ed87f08634d',
    messagingSenderId: '711457422776',
    projectId: 'cepuapp-35e84',
    storageBucket: 'cepuapp-35e84.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO0H1SXf6J5hNusuuWxUA8OkTTp8IAb_Y',
    appId: '1:711457422776:web:f17c02e41971c56c08634d',
    messagingSenderId: '711457422776',
    projectId: 'cepuapp-35e84',
    authDomain: 'cepuapp-35e84.firebaseapp.com',
    storageBucket: 'cepuapp-35e84.firebasestorage.app',
    measurementId: 'G-4G4GZP98YJ',
  );
}
