// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDASZ3eQ4f64XUB2vNdgFIRNQaDFIm1Aj8',
    appId: '1:980670197654:web:428280b5f358d2208db7b7',
    messagingSenderId: '980670197654',
    projectId: 'notes-38766',
    authDomain: 'notes-38766.firebaseapp.com',
    storageBucket: 'notes-38766.firebasestorage.app',
    measurementId: 'G-BCZKS88920',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ418pD2xwchK6RRt5Rjsch09HpYEJ8fc',
    appId: '1:980670197654:android:4e6745af99edfee78db7b7',
    messagingSenderId: '980670197654',
    projectId: 'notes-38766',
    storageBucket: 'notes-38766.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuO_HPdfOKx5fh2f5GtFWqcTR49Gt8a94',
    appId: '1:980670197654:ios:020bce31f3d8cfa38db7b7',
    messagingSenderId: '980670197654',
    projectId: 'notes-38766',
    storageBucket: 'notes-38766.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuO_HPdfOKx5fh2f5GtFWqcTR49Gt8a94',
    appId: '1:980670197654:ios:020bce31f3d8cfa38db7b7',
    messagingSenderId: '980670197654',
    projectId: 'notes-38766',
    storageBucket: 'notes-38766.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDASZ3eQ4f64XUB2vNdgFIRNQaDFIm1Aj8',
    appId: '1:980670197654:web:349229e32d06699c8db7b7',
    messagingSenderId: '980670197654',
    projectId: 'notes-38766',
    authDomain: 'notes-38766.firebaseapp.com',
    storageBucket: 'notes-38766.firebasestorage.app',
    measurementId: 'G-DYMTWTTYH7',
  );
}
